//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajoempleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATISTAS
    {
        public int Id { get; set; }
        public string IdContratista { get; set; }
        public string Rnc { get; set; }
        public string NombreEmpresa { get; set; }
        public string Representante { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Contrasena { get; set; }
        public string Direccion { get; set; }
        public string Descripcion { get; set; }
    }
}
