//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajoempleados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEOS
    {
        public int Id { get; set; }
        public string IdEmpleo { get; set; }
        public string IdEmpresa { get; set; }
        public string Empresa { get; set; }
        public string Tipo { get; set; }
        public byte[] Logo { get; set; }
        public string Posicion { get; set; }
        public string Ubicacion { get; set; }
        public string Categoria { get; set; }
        public string Descripcion { get; set; }
        public string caplicar { get; set; }
        public string Email { get; set; }
        public string Fechapubli { get; set; }
        public string Urlx { get; set; }
    }
}
