//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajoempleados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bolsaempleosEntities : DbContext
    {
        public bolsaempleosEntities()
            : base("name=bolsaempleosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADORES> ADMINISTRADORES { get; set; }
        public virtual DbSet<CANDIDATOS> CANDIDATOS { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CONTRATISTAS> CONTRATISTAS { get; set; }
        public virtual DbSet<EMPLEOS> EMPLEOS { get; set; }
    
        public virtual ObjectResult<busca_categoria_Result> busca_categoria(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busca_categoria_Result>("busca_categoria", nombreParameter);
        }
    
        public virtual ObjectResult<busca_categoria2_Result> busca_categoria2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<busca_categoria2_Result>("busca_categoria2", idParameter);
        }
    }
}
