//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajoempleados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bolsaempleosEntities : DbContext
    {
        public bolsaempleosEntities()
            : base("name=bolsaempleosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADORES> ADMINISTRADORES { get; set; }
        public virtual DbSet<CANDIDATOS> CANDIDATOS { get; set; }
        public virtual DbSet<CONTRATISTAS> CONTRATISTAS { get; set; }
        public virtual DbSet<EMPLEOS> EMPLEOS { get; set; }
    }
}
